package de.fegbers.dependencies.maven.plugin.mojo;

import static java.util.Arrays.asList;
import static org.easymock.EasyMock.expectLastCall;
import static org.junit.Assert.assertTrue;
import static org.powermock.api.easymock.PowerMock.replayAll;
import static org.powermock.api.easymock.PowerMock.verifyAll;
import static org.powermock.reflect.Whitebox.setInternalState;

import java.io.File;
import java.nio.charset.Charset;

import org.apache.commons.io.FileUtils;
import org.apache.maven.model.Dependency;
import org.apache.maven.project.MavenProject;
import org.easymock.TestSubject;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.powermock.api.easymock.annotation.MockStrict;
import org.powermock.modules.junit4.PowerMockRunner;

@RunWith(PowerMockRunner.class)
public class DependenciesMojoTest
{
	@TestSubject
	private DependenciesMojo dependenciesMojo = new DependenciesMojo();

	@MockStrict
	private MavenProject project;

	@MockStrict
	private Dependency dependency1;

	@MockStrict
	private Dependency dependency2;

	@Before
	public void before()
	{
		setInternalState(dependenciesMojo, "src/test/resources/dependencies.properties");
	}

	@Test
	public void testExecute() throws Exception
	{
		project.getDependencies();
		expectLastCall().andReturn(asList(dependency1, dependency2));

		dependency1.getManagementKey();
		expectLastCall().andReturn("de.fegbers:dependency1:jar");

		dependency1.getVersion();
		expectLastCall().andReturn("1.1.4-RELEASE");

		dependency2.getManagementKey();
		expectLastCall().andReturn("de.fegbers:dependency2");

		dependency2.getVersion();
		expectLastCall().andReturn("0.5.3");

		replayAll();
		dependenciesMojo.execute();
		verifyAll();

		File dependenciesProperties = new File("src/test/resources/dependencies.properties");
		assertTrue(dependenciesProperties.exists());
		String fileContent = FileUtils.readFileToString(dependenciesProperties, Charset.defaultCharset());
		assertTrue(fileContent.contains("#Generated by dependency-maven-plugin"));
		assertTrue(fileContent.contains("dependency_de_fegbers_dependency1_jar=1.1.4-RELEASE"));
		assertTrue(fileContent.contains("dependency_de_fegbers_dependency2=0.5.3"));
	}
}
